### ISSUE TITLE
Deprecated PHP with curly braces

### ISSUE THREAD

**Issue by wintermoor** [totten/civix#205]
Many extensions are showing this error with CiviCRM 5.35.beta1 and PHP 7.4.3:
Deprecated:Array and string offset access syntax with curly braces is deprecated 

It's in _EXTENSIONNAME_.civix.php (often around line 243-47): 
  if ($entry{0} == '.') {
must be replaced by 
  if ($entry[0] == '.') {

This file is generated from Civix.

**Comment by seamuslee001** [comment]
this has already been fixed in the template see https://github.com/totten/civix/blob/master/src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php#L251 however extension Authors need to have the latest civix version and then re-run civix generate:module within their extension to get the latest updates

**Comment by wintermoor** [comment]
Didn't see this, thank you for clarification @seamuslee001 
I'll close this issue now.
