### ISSUE TITLE
Have CiviX generate `<authors>` info.xml instead of `<maintainer>`

### ISSUE THREAD

**Issue by homotechsual** [totten/civix#208]
We should look at adding support for `<authors>` to the Civix workflows as well as/instead of Maintainer.

**Comment by totten** [comment]
As far as core support goes, this will go out in 5.36.

It might help if we had some (new?) example ext published with `<authors>` so that we could check if the distribution channel works well with it.

If it does, then I suppose one could switch to `<authors>` if we also set a default `<ver>5.36</ver>`?
