### ISSUE TITLE
Teach civix about the afform-entity-php@1.0.0 mixin

### ISSUE THREAD

**Issue by aydun** [totten/civix#246]
This mixin is required for extensions creating afformEntities.  Civix does not know about it.  The mixin can be added manually to info.xml but future calls to civix fail with:

```
In Mixlib.php line 184:
                                                                                                                      
  Failed to locate afform-entity-php@1/mixin.php (mixlibDir=phar:///opt/buildkit/bin/civix/extern/mixin, mixlibUrl=)  
```

fyi @colemanw

**Comment by colemanw** [comment]
@totten I'm confused about this. I don't see hardcoded references to specific mixins in civix. Doesn't it just scan `civicrm-core/mixin` for those? Why isn't this working?

**Comment by totten** [comment]
This issue should be fixed by d8e980e70f7057ebb42c6a1da9972444313683f8 / v22.06.2.

@colemanw The list is `mixin-backports.php`. You may recall - the testing+metadata+requirements for backports are more fiddly/stringent than for regular code updates, and it's easier on my brain if that responsibility is split (ie `civicrm-core` drives new iterations of the mixins per SemVer; then `civix` decides backports). 

The bit that might be surprising - civix currently wants `mixin-backports.php` to have a full list (even if you don't intend to use backports).  It's easy to update. It would be nice to work better with non-backported mixins, though I'm not sure how easy it is to support both.

Question/aside: `afform-entity-php@1` is provided by 5.50. Is that also the minimum to use it? Or does it also work on prior versions?

**Comment by colemanw** [comment]
@totten this mixin has a bit of a weird upgrade path:

- `< 5.50` the mixin is not needed because core does the file scanning automatically
- `>= 5.50` the mixin is required if you want to keep doing the file scanning

So for an extension to be compatible with all versions, it should add the mixin tag to `info.xml` and then provide an empty shim that does nothing, like this: https://github.com/eileenmcnaughton/deduper/pull/26/files

**Comment by totten** [comment]
@colemanw Re-reading, perhaps https://github.com/totten/civix/commit/d8e980e70f7057ebb42c6a1da9972444313683f8 wasn't the correct revision?

* That would have the effect of copying https://raw.githubusercontent.com/civicrm/civicrm-core/5.50.0/mixin/afform-entity-php@1/mixin.php (*let's call it `1.0.0-real`*) into an extension.
* But any system which needs that revision already has it.
* The copied file only matters when running on older systems.
* Older systems should have https://raw.githubusercontent.com/colemanw/deduper/6791ae0b70db3790ac4508a69c54498c13dbf111/mixin/afform-entity-php%401/mixin.php (*let's call it `1.0.0-null`*) (*mostly so that they don't error-out on the missing file).

Additional question: for systems <5.50, how far back does it go? Like it's meaningful to use `1.0.0-null` on, say, 5.30?

**Comment by totten** [comment]
There appears to be some afformEntity scanning code as far back as https://github.com/civicrm/civicrm-core/commit/0406c8f9babc630b2c85fb14875329462a91ee15#diff-b700bdf29c94b8c86727852b07277f33787500b5af297c2fc5c86105ec0edc50R191. So maybe the minimum is 5.31

**Comment by totten** [comment]
Aah, wait. The only behavior of `v1.0.0-real` is to subscribe to `civi.afform_admin.metadata` -- which won't be emitted on 5.31-5.49. `v1.0.0-real` and `v1.0.0-null` are both nullops. It shouldn't matter which variant we use for backport purposes.

The only difference is that `v1.0.0-null` provides better comments. We could add more comments to `v1.0.0-real` -- and then we don't need two versions of the file?
