### ISSUE TITLE
php codesniffer warnings

### ISSUE THREAD

**Issue by jofranz** [totten/civix#294]
`phpcs -p . --standard=PHPCompatibility --runtime-set testVersion 7.4-8.1`

Civix version: 23.02.1

```
FILE: de.systopia.xcm/mixin/polyfill.php
----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------------------------------------------------------------------------------------------
 52 | WARNING | Closures / anonymous functions only have access to $this if used within a class or when bound to an object using bindTo(). Please verify.
 56 | WARNING | Closures / anonymous functions only have access to $this if used within a class or when bound to an object using bindTo(). Please verify.
----------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: de.systopia.xcm/mixin/smarty-v2@1.0.0.mixin.php
----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------
 25 | WARNING | Closures / anonymous functions only have access to $this if used within a class or when bound to an object using bindTo(). Please verify.
----------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by totten** [comment]
For `polyfill.php`, the usage of `$this` looks fine to me. But I wouldn't be surprised if their pattern-matcher was little off. (*This is anonymous class inside an anonymous function... which is not very common.*)

For `smarty-v2@1.0.0`, that probably is a latent bug (*i.e. code is wrong; but currently I can't see a symptom*). Fortunately, Eileen posted an update for `smarty-v2@1.0.1` which incidentally fixes that. So I'll update the backport to use it.

**Comment by totten** [comment]
Thanks for reporting @jofranz. v23.03.0 is up and should include a fix for the `smarty-v2` issue.

The `polyfill.php` is more awkward - since it looks like a false-negative to me. A few ways to go:

* Ignore it. (*That's easiest from my POV...*)
* Send a PR to [the canonical `polyfill.php`](https://github.com/civicrm/civicrm-core/blob/master/mixin/polyfill.php) and sprinkle in [something like `phpcs:ignore`](https://stackoverflow.com/questions/16039362/how-can-i-suppress-phpcs-warnings-using-comments). (*After that, we'd [update civix](https://github.com/totten/civix/blob/master/mixin-backports.php).*)
* Open an issue for `phpcs`/`PHPCompatibility`. Give them an example to test (e.g. an anonymous-class inside an anonymous-function).
