### ISSUE TITLE
Civix 23.08.1 Fatal Error with php 7.4

### ISSUE THREAD

**Issue by kcristiano** [totten/civix#307]
Running civix (any command)  version 23.08.1  on php 7.4.33 (debian) 

The following error occurs

```
Fatal error: Uncaught Error: Interface 'Stringable' not found in phar:///home/cividev/bin/civix/vendor/symfony/polyfill-php80/PhpToken.php:18
Stack trace:
#0 phar:///home/cividev/bin/civix/.box/vendor/composer/ClassLoader.php(582): include()
#1 phar:///home/cividev/bin/civix/.box/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 phar:///home/cividev/bin/civix/vendor/symfony/polyfill-php80/Resources/stubs/PhpToken.php(14): spl_autoload_call()
#4 phar:///home/cividev/bin/civix/.box/vendor/composer/ClassLoader.php(582): include('phar:///home/ci...')
#5 phar:///home/cividev/bin/civix/.box/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#7 phar:///home/cividev/bin/civix/vendor/autoload.php(37): spl_autoload_call()
#8 phar:///home/cividev/bin/civix/vendor/autoload.php(45): humbug_phpscoper_expose_class()
#9 phar:///home/cividev/bin/civix/bin/civix(19): req in phar:///home/cividev/bin/civix/vendor/symfony/polyfill-php80/PhpToken.php on line 18
```

using php 8.0.x or 8.1.x works properly

**Comment by totten** [comment]
oye. I totally get that problem too. I'm not sure why it didn't appear on test matrix before publishing. Looking...

**Comment by totten** [comment]
[Oh, right](https://github.com/civicrm/civicrm-buildkit/blob/master/src/jobs/CiviCRM-Civix-Matrix.job#L74-L76) -- `box` has to do the compilation step in php8. And we have to test both src-execution and phar-execution. The tester does an "easy" work-around (running along the "diagonal" -- (`php7, --src` and `php8, --phar`). It really should check more permutations. So that's probably why the test didn't catch it. 

Now why does the php80 polyfill depend on a php80 interface that's not available...

**Comment by totten** [comment]
Patch: #308

**Comment by totten** [comment]
civix v23.08.2 released with patch.
