### ISSUE TITLE
Add Instructions to Install with Composer

### ISSUE THREAD

**Issue by davidbarratt** [totten/civix#34]
Instead of using Git to install Civix, perhaps it would be better to use Composer?
https://getcomposer.org/doc/03-cli.md#global

This is also the way Drush handles installation now:
https://github.com/drush-ops/drush#installupdate---composer

Thanks!

**Comment by totten** [comment]
#35 was previously merged - but forgot to update the issue.

**Comment by totten** [comment]
The 2016 versions of `civix` (e.g. v16.02.0+) were refactored to provide a standalone executable (PHAR) rather than a Symfony SE project. This significantly simplifies the directory structure and should make it easier to install different ways.

In the interim (since this issue was filed), `drush`  has also changed their distribution practice to recommend PHAR by default. When juggling multiple executables, multiple versions, conflicting dependencies, etc, the PHAR files are more flexible+consistent.

If there are any more patches needed to support `composer global require`, they'll be welcome, but it's not a priority.
