### ISSUE TITLE
CiviCRM not found if in profiles/*/modules

### ISSUE THREAD

**Issue by ixiam** [totten/civix#49]
CiviCRM is not found when executing civix civicrm:ping if it's located in  profiles/*/modules/[contrib]/

**Comment by totten** [comment]
I took a quick stab at this (https://github.com/totten/civix/compare/7bce74e97...4b8bf7b32) and verified that it now finds ```civicrm.config.php``` in that folder. It generated a different error, but this may be because (a) I was too lazy to do a full custom build+install to replicate the profiles configuration or (b) core's ```civicrm.config.php``` doesn't work when placed under ```profiles``` (with some special work-around... maybe settings_location.php?).

```
Could not load the settings file at: /Users/foo/buildkit/build/d46/profiles/minimal/modules/civicrm/../..//default/civicrm.settings.php
```

However, that's out-of-scope of civix. If there's a problem with ```civicrm.config.php```, then I'm sure it's patch-welcome in core.
