### ISSUE TITLE
Generating API extension broken

### ISSUE THREAD

**Issue by keirlawson** [totten/civix#58]
```
$ civix generate:api NewEntity NewAction
PHP Fatal error:  Call to a member function attributes() on null in /home/keir/Code/PHP/civix/src/CRM/CivixBundle/Builder/Info.php on line 62

Fatal error: Call to a member function attributes() on null in /home/keir/Code/PHP/civix/src/CRM/CivixBundle/Builder/Info.php on line 62
```

**Comment by adam-edison** [comment]
I had a similar error message today:

Call to a member function attributes() on null in /usr/local/lib/civicrm-buildkit/extern/civix/src/CRM/CivixBundle/Builder/Info.php on line 62

1. Are you running this command from inside your extension folder (e.g. com.mycompany.module)?
2. Are you running this command without a skeleton in place? You might need to run **civix generate:module** first.
3. Finally, make sure your extension folder is inside a working web root folder (or you'll get an error like this: [Exception] Failed to locate CMS. Please call civix from somewhere under the CMS root.).

For my case, I had a symlink pointing to my extension directory. I was directly inside the extension directory and got the [Exception] mentioned above, because it's not inside a web root.

So I navigated to my web root and ran my civix command.
Then I got your Info.php error message.
I had to navigate inside webroot/sites/default/ext/myext and run my civix command.

Hope this helps you out!

**Comment by totten** [comment]
Thank you for the description, @adam-edison.

I'll take a quick stab at providing a clearer error message.

For reference, when getting started with `civix`, I recommend the tutorial at https://wiki.civicrm.org/confluence/display/CRMDOC/Create+a+Module+Extension The example commands always demonstrate how to handle `cd` and CWD (and there are also more explanatory bits and links to more in-depth documentation).

**Comment by totten** [comment]
With 4fba1dcaa7, error messages in v16.03.0 should be clearer.
