### ISSUE TITLE
civix civicrm:ping not printing any output

### ISSUE THREAD

**Issue by jasonroseweir** [totten/civix#65]
I am running CiviCRM on Mac OSX 10.11.3, using the latest Bitnami CiviCRM/Drupal stack (bitnami-civicrm-4.6.11-0-osx-x86_64). I have civix-15.04.1 installed as instructed (under $HOME/civix), and have it added to the path. Likewise I have updated the PATH to use the version of PHP provided by the stack.

While I can use civix successfully to run commands like:

`$ civix generate:module`

when I try and run the following command (as a pre-req to generating custom-xml):

`$ civix civicrm:ping`

I get no output whatsoever.

I am running the command from within the web root.

**Comment by totten** [comment]
I've installed the same build from Bitnami (civicrm-4.6.11-0). Some observations:

 * I can confirm that you need to use Bitnami's PHP (e.g. `export PATH=/Applications/civicrm-4.6.11-0/php/bin:$PATH`). The issue here is that the DSN set in `civicrm.settings.php` implicitly relies on some defaults in the PHP build (e.g. the default mysqld socket). (For DSN's to be portable across PHP builds, it helps to specify IP+port.)
 * You probably saw this already, but to verbalize: the web root is `/Applications/civicrm-4.6.11-0/apps/civicrm/htdocs`. To try it out, I made a new dir `/Applications/civicrm-4.6.11-0/apps/civicrm/htdocs/sites/all/modules/civicrm/tmp` and put stuff there.
 * Instead of using civix 15.04.1, I used the newer v16.02.0 and v16.02.1 (PHAR). The commands `civicrm:ping`, `generate:module`, `generate:custom-xml`, and `generate:upgrader` all worked.

**Comment by totten** [comment]
Please give it a try with the current version.

If you get errors, it may help to pass `-v`.

Feel free to reopen.
