### ISSUE TITLE
Command not define

### ISSUE THREAD

**Issue by flik** [totten/civix#67]
civix generate:report-ext --help

This command is not working and giving this message.
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "generate:report-ext" is not defined.                   
  Did you mean one of these?                                      
      generate:report                                             
      generate:page                                               
      generate:search                                             
      generate:test                                               
      generate:module                                             
      generate:upgrader                                           
      generate:form                                               
      generate:entity                                             
      generate:angular-page                                       
      generate:angular-module                                     
      generate:api                                                
      generate:case-type                                          
      generate:custom-xml                                         
      generate:angular-directive

**Comment by totten** [comment]
`generate:report-ext` produced a narrowly crafted report extension. That practice has been deprecated since Civi v4.2. `generate:report-ext` was finally removed in v16.02.0 ([CHANGELOG](https://github.com/totten/civix/blob/master/CHANGELOG.md#v16020)). The recommended practice is to create a module extension (use `generate:module`) and include a report class (`generate:report`).

See also:
 * https://github.com/totten/civix/blob/master/CHANGELOG.md#v16020
 * https://wiki.civicrm.org/confluence/display/CRMDOC/Create+an+Extension
 * https://wiki.civicrm.org/confluence/display/CRMDOC/Create+a+Module+Extension#CreateaModuleExtension-Addareport
