### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by eileenmcnaughton** [totten/civix#68]
Hi

I just did Civix update & found it broken & there seemed to be things I needed to install and download and after 15-20 mins I decided to check out an earlier version and not get drawn into spending time on Civix.

The upshot being that I think when you introduce breaking changes it's probably worth tagging the prior commit as being a release or something so people who don't want to spend time on it can use that tag until they are ready to.

This is on my windows box & the issues may be related to that - but my main focus is backing out of this & getting back to where things were working so I can deal with my angular extension stuff being broken on 4.7

**Comment by eileenmcnaughton** [comment]
NB - back on

commit 4ae3ee4473c2f5ab32eb0b913e79c2ea4949a242
Author: Tim Otten <totten@civicrm.org>
Date:   Fri Feb 5 21:18:22 2016 -0800

    scripts/export - Add script to generate tarball (without tagging)

it seems to work again

**Comment by totten** [comment]
Yeah, that could have been handled better.

It's been a long time since I advised doing a git-based installation, but - on inspection - you're right that there was a breaking change. The path to the main executable changed from `./civix` and `./civix.bat` to `./bin/civix`. Any other changes should be handled with simple/standard `composer install`.

Updates:
 * Added note to CHANGELOG (bc11622) 
 * Pushed a tag, `v15.last`. This corresponds to the [last tarball](download.civicrm.org/civix/civix-2016-02-05-4ae3ee44.tar.bz2) (pre-PHAR). 
 * Posted a PSA to http://lists.civicrm.org/lists/info/civicrm-dev
