### ISSUE TITLE
'cv' is not recognized as internal or external command

### ISSUE THREAD

**Issue by digitlimit** [totten/civix#69]
I get this error when I run : 

`civix generate:api EntityName ActionName`

'cv' is not recognized as an internal or external command,
operable program or batch file.

  [RuntimeException]
  Command failed (cv php:boot --level=full):
generate:api [--schedule [SCHEDULE]] [--] <<EntityName>> <<ActionName>>

I am using  windows

**Comment by totten** [comment]
1. Generally speaking, the goal is to put both `civix` and `cv` PHAR executables in the `PATH`. I don't have a list of steps for that in Windows (mostly because I don't use Windows; but also because the Windows-PHP community has an unenviable variety of runtimes). It's odd that `civix` is callable, while `cv` is not. Did you do something different when installing `civix` and `cv`?

2. Any idea how other PHAR executables -- like `composer`, `phpunit`, or `symfony` -- are handled on Windows?
 
3. I have only a few hints about changes that might better facilitate Windows. Don't know how important these are.
  a. The `HOME` variable may not be defined in Windows. In `v15.last`, there was a wrapper script https://github.com/totten/civix/blob/v15.last/civix.bat which manipulated HOME. Similar logic could be put into `bin/civix`. (Maybe: `if (!getenv(HOME)) { putenv(HOME=getenv(USERPROFILE)); }`)
  b. If Windows is really persnickity about registering PHAR commands, we could remove the `cv` dependency. Fundamentally, we only need one file from `cv` (https://github.com/civicrm/cv/blob/master/src/Bootstrap.php). It's just a bit of administration to that get that file packaged.

**Comment by totten** [comment]
Published updated `civix.phar`. It removes requirement to have `cv` and should look for a different HOME dir. (However, I can't test it on Windows.)
