### ISSUE TITLE
i had #73 after updating and run civix.bat i got this 

### ISSUE THREAD

**Issue by solve-it** [totten/civix#74]
Fatal error: Class 'Civi\Cv\Bootstrap' not found in C:\xampp\htdocs\civix\src\CRM\CivixBundle\Services.php on line 20

**Comment by solve-it** [comment]
if it will help this is the directory and the command am running   
/c/xampp/htdocs/extension/com.idealitsolutions.contactcampaign (dev)
$ civix.bat generate:api Pcp get

**Comment by totten** [comment]
You probably needed to run `composer install` again. That's a general matter of working with git+composer: after updating the git repo, the `composer.json` and `composer.lock` files may have changed. (Specifically, around the time of #70/#73, the `composer.json` did change -- so that the class `Civi\Cv\Bootstrap` would be available.) Running `composer install` should update the dependencies.
