### ISSUE TITLE
Add --short-name option to generate:module

### ISSUE THREAD

**Issue by seancolsen** [totten/civix#95]
When I run `civix generate:module org.civicrm.foo.bar` I get an extension with a short name of `bar`. If, instead, I'd like to have my short name be `foobar` then it's really better for me to run without the dot first and change the key afterwards. It would be nice if `civix` had an option `--short-name` where I could pass in a custom short name like this: 

`civix generate:module --short-name=foobar org.civicrm.foo.bar`

**Comment by totten** [comment]
In theory, just patch https://github.com/totten/civix/blob/master/src/CRM/CivixBundle/Command/InitCommand.php to `addOption('short-name'...)` and populate `$ctx['mainFile']` with `$input->getOption('short-name')` (when applicable). But it needs to be written+tested to ensure that the resulting module works.

**Comment by totten** [comment]
Closing. In practice, I think that #236 addressed the main issue. We now encourage `civix generate:module NAME` without any dots, so that the long+short names are identical.

It would still be fine to support `--short-name` if someone implements it, but I don't think there's a need to keep an issue open for it.
